apiVersion: v1
kind: Service
metadata:
  name: echo-get-loadbalancer
  annotations:
    service.beta.kubernetes.io/do-loadbalancer-protocol: "http"
    service.beta.kubernetes.io/do-loadbalancer-size-slug: "lb-small"
spec:
  type: LoadBalancer
  selector:
    run: echo-get-pod
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 5000
