apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo-get-deployment
spec:
  selector:
    matchLabels:
      run: echo-get-pod
  replicas: 2
  template:
    metadata:
      labels:
        run: echo-get-pod
    spec:
      containers:
        - name: echo-get-container
          #image: python:3.9
          #command: ["tail", "-f", "/etc/passwd"]
          #myflask:1.00
          image: registry.digitalocean.com/szabgab-demo/myflask:1.00
          imagePullPolicy: Always
          #imagePullPolicy: Never
          ports:
            - containerPort: 5000

