apiVersion: v1
kind: Service
metadata:
  name: echo-get-service
  labels:
    run: echo-get-service
spec:
  ports:
  - port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    run: echo-get-deployment
  type: NodePort
