version: '3.8'
services:
  client:
    build: .
    volumes:
    - .:/opt
    links:
    - mysql
    command: tail -f /dev/null
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: secret

