[package]
name = "say-hello-many-times-use"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
say-hello-many-times-macro = { version = "0.1.0", path = "../say-hello-many-times-macro" }
