build:
    stage: build
    script: echo Build

test:
    stage: test
    script: echo Test

deploy:
    stage: deploy
    when: manual
    script:
        - echo Check Deploy
        - echo $CODE
        - if [ "$(echo -n $CODE | sha256sum)" == "2bb80d537b1da3e38bd30361aa855686bde0eacd7162fef6a25fe97bf527a25b  -" ]; then echo ok; else exit 1; fi
        - echo Deploy
