version: '3.7'
services:
  web:
    build: .
    ports:
    - "5001:5000"
    volumes:
    - .:/opt
    links:
    - pulsar
  pulsar:
    image: apachepulsar/pulsar:2.5.2
    container_name: my-pulsar
    expose:
       - 8080
       - 6650
    command: >
      /bin/bash -c
      "bin/apply-config-from-env.py conf/standalone.conf
      && bin/pulsar standalone"
#  dashboard:
#    image: apachepulsar/pulsar-dashboard
#    depends_on:
#      - pulsar
#    ports:
#      - "5002:80"
#    environment:
#      - SERVICE_URL=http://pulsar:8080
