name: OS Matrix

on: push

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        runner: [ubuntu-latest, macos-latest, windows-latest]

    runs-on: ${{matrix.runner}}
    steps:
    - uses: actions/checkout@v2

    - name: View environment
      run: |
        uname -a
        printenv | sort

