import os,shutil,glob
"""
Remove the files generated by python setup.py build|sdist
"""



for thing in glob.glob('mymath*'):
    #print thing
    for subdir in ('mymath.egg-info', 'dist', 'build'):
       path = os.path.join(thing, subdir)
       print(path)
       if os.path.isdir(path):
           shutil.rmtree(path)

