name: NodeJS

on:
    push:
    pull_request:

jobs:
  nodejs:
    strategy:
      fail-fast: false
      matrix:
        runner: [ubuntu-latest]
        nodejs: [ 18.16 ]

    runs-on: ${{matrix.runner}}
    name: OS ${{matrix.runner}} NodeJS ${{matrix.nodejs}}

    steps:
    - name: Checkout this repo
      uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.nodejs }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.nodejs }}

    #- name: Show NodeJS Version
    #  run: |
    #    node -v
    #    cd nodejs
    #    npm install
    #    npm test

